airflow:
  executor: KubernetesExecutor
workers:
  enabled: false
flower:
  enabled: false
redis:
  enabled: false
web:
  service:
    type: NodePort
postgresql:
  enabled: false
externalDatabase:
  type: postgres
  host: postgres.posgres
  port: 5432
  database: airflow
  user: airflow
  passwordSecret: "airflow-secret"
  passwordSecretKey: "airflow-postgres-password"
dags:
  persistence:
    enabled: true
    storageClass: standard
    accessMode: ReadOnlyMany
    size: 10Mi
#dags:
#  gitSync:
#    enabled: true
#    #repo: "git@github.com:software-foundry/dags.git"
#    #sshSecret: "airflow-ssh-git-secret"
#    repo: "https://github.com/software-foundry/dags.git"
#    httpSecret: "airflow-http-git-secret"
#    branch: "master"
#    revision: "HEAD"
#    syncWait: 60
#    maxFailures: 3
#    sshKnownHosts: |-
#      github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==

