apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgres
  namespace: postgres
spec:
   replicas: 1
   image: postgres:13.2
   database:
      size: 200Mi
   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-secret
              key: superUserPassword
      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-secret
              key: replicationUserPassword
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: postgres
  labels:
    app: postgres
    replicationRole: primary
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
  selector:
    app: postgres
    replicationRole: primary
  type: LoadBalancer

